改变更新架构
XMOJ-Script-dev/XMOJ-Script pull request #301
Opened 2023-12-15 12:49 UTC by boomzero

- [ ] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2023-12-15 13:07 UTC, boomzero commented
Well, seems to work

2023-12-15 13:23 UTC, boomzero commented
done, I think

2023-12-15 14:06 UTC, boomzero commented
finally, success!

2023-12-15 14:07 UTC, boomzero commented
v1.1.3是故意的，测试manual bump version

2023-12-15 14:26 UTC, boomzero commented
@langningchen Ready for review

2023-12-16 00:11 UTC, langningchen commented
@boomzero 好的，我看一下

2023-12-16 00:13 UTC, langningchen commented
最后一位版本号不应当清理

2023-12-16 00:24 UTC, langningchen commented
patch 是累加的，我原来不清零他不是因为做不到，而是因为不需要

2023-12-16 00:24 UTC, langningchen commented
一个patch版本号能表示该项目被发布了多少次

2023-12-16 00:25 UTC, langningchen requested changes

2023-12-16 00:25 UTC, langningchen commented on XMOJ.user.js
> +// @version      1.1.2
你最后一位还是保留一下吧

2023-12-16 00:34 UTC, boomzero commented
但是I think这样不符合npm的标准

> On Dec 16, 2023, at 08:25, Langning Chen ***@***.***> wrote:
> 
> 
> 一个patch版本号能表示该项目被发布了多少次
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/301#issuecomment-1858635472>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AULMJZLNR2FU3MSPGRR6733YJTS6DAVCNFSM6AAAAABAWM277SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTQNJYGYZTKNBXGI>.
> You are receiving this because you were mentioned.
>

2023-12-16 00:34 UTC, boomzero commented
现在bump version用的是npm version minor, 会自动清零patch

> On Dec 16, 2023, at 08:25, Langning Chen ***@***.***> wrote:
> 
> 
> @langningchen requested changes on this pull request.
> 
> In XMOJ.user.js <https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/301#discussion_r1428607490>:
> 
> > @@ -1,6 +1,6 @@
>  // ==UserScript==
>  // @name         XMOJ
> -// @version      1.1.1
> +// @version      1.1.2
> 你最后一位还是保留一下吧
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/301#pullrequestreview-1785075178>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AULMJZNTGZJD7Q7UKCA5WQTYJTTAXAVCNFSM6AAAAABAWM277SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBVGA3TKMJXHA>.
> You are receiving this because you were mentioned.
>

2023-12-16 00:37 UTC, boomzero commented on XMOJ.user.js
> +// @version      1.1.2
现在bump version用的是npm version minor, 会自动清零patch

2023-12-16 00:39 UTC, boomzero commented
> patch 是累加的，我原来不清零他不是因为做不到，而是因为不需要

emm, I think this is neccessary

2023-12-16 04:59 UTC, langningchen approved these changes
如果是为了符合 `npm` 的标准，那么就这样吧

2023-12-16 05:34 UTC, boomzero commented
Ok, thx

> On Dec 16, 2023, at 12:59, Langning Chen ***@***.***> wrote:
> 
> 
> @langningchen approved this pull request.
> 
> 如果是为了符合 npm 的标准，那么就这样吧
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/XMOJ-Script-dev/XMOJ-Script/pull/301#pullrequestreview-1785129707>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AULMJZKRIDOHZ53UVZRHEN3YJUTCDAVCNFSM6AAAAABAWM277SVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTOOBVGEZDSNZQG4>.
> You are receiving this because you were mentioned.
>

2023-12-16 05:34 UTC, merged

2023-12-16 07:07 UTC, boomzero commented
🎉 https://www.npmjs.com/package/xmoj-script

2023-12-16 10:01 UTC, PythonSmall-Q commented
wow！