遇到"比赛尚未开始或私有，不能查看题目。"时自动跳转回”竞赛&作业”页面
XMOJ-Script-dev/XMOJ-Script pull request #542
Opened 2024-05-29 12:27 UTC by zhouyiqing0304

PR#541

- [x] 我已认真阅读贡献指南 (contributing guidelines) 和社区公约 (code of conduct)，并遵循了如何参与页及格式手册页的相应规范。

2024-05-30 08:47 UTC, zhouyiqing0304 commented
@PythonSmall-Q 
来过一下？

2024-06-01 02:10 UTC, PythonSmall-Q commented
我说了，请向externcontrib分支发PR，否则action会炸

在 2024-05-30 16:48:11，zhouyiqing0304 ***@***.***> 写道：


@PythonSmall-Q
来过一下？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-06-01 02:12 UTC, PythonSmall-Q commented
***@***.***，让他来搞，现在我不太方便上github


在 2024-06-01 10:10:15，seanoj_noreply ***@***.***> 写道：
我说了，请向externcontrib分支发PR，否则action会炸

在 2024-05-30 16:48:11，zhouyiqing0304 ***@***.***> 写道：


@PythonSmall-Q
来过一下？

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-06-01 02:57 UTC, boomzero requested changes
跳转到上一页

2024-06-01 10:26 UTC, zhouyiqing0304 commented
![image](https://github.com/XMOJ-Script-dev/XMOJ-Script/assets/94766918/27433d0e-e557-409c-9d2b-ff085d3e606d)
?

> externcontrib

我确实这么提交了啊

2024-06-01 13:44 UTC, PythonSmall-Q commented
我看错了，不好意思。现在我是用邮箱看的，看不清branch搞错了




--
发自我的网易邮箱手机智能版



在 2024-06-01 18:26:59，zhouyiqing0304 ***@***.***> 写道：


image.png (view on web)
?

externcontrib

我确实这么提交了啊

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-06-09 12:04 UTC, zhouyiqing0304 commented
?

2024-06-10 11:30 UTC, PythonSmall-Q commented
我们这边想让你把代码改成如果未开始就返回上一个页面而不是回到contest页面，因为有可能用户从不同的入口进来



--
发自我的网易邮箱手机智能版



在 2024-06-09 20:05:18，zhouyiqing0304 ***@***.***> 写道：


?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-06-12 00:48 UTC, boomzero commented
true

Sent from my iPad

> On Jun 10, 2024, at 19:30, Shan Wenxiao ***@***.***> wrote:
> 
> ﻿
> 我们这边想让你把代码改成如果未开始就返回上一个页面而不是回到contest页面，因为有可能用户从不同的入口进来
> 
> 
> 
> --
> 发自我的网易邮箱手机智能版
> 
> 
> 
> 在 2024-06-09 20:05:18，zhouyiqing0304 ***@***.***> 写道：
> 
> 
> ?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.Message ID: ***@***.***>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you commented.

2024-06-18 00:00 UTC, boomzero commented
So...

2024-06-18 00:00 UTC, boomzero commented
Interaction limits have been disabled

2024-06-18 12:02 UTC, PythonSmall-Q commented
> Interaction limits have been disabled

what do you mean

2024-06-19 02:36 UTC, boomzero commented
> > Interaction limits have been disabled
> 
> what do you mean

emm...

2024-06-20 08:31 UTC, zhouyiqing0304 commented
> 我们这边想让你把代码改成如果未开始就返回上一个页面而不是回到contest页面，因为有可能用户从不同的入口进来
> […](#)
> -- 发自我的网易邮箱手机智能版 在 2024-06-09 20:05:18，zhouyiqing0304 ***@***.***> 写道： ? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

ok稍等亿会

2024-06-21 03:45 UTC, PythonSmall-Q commented
改完了之后别忘了申请re-review

2024-06-24 11:52 UTC, shanwenxiao commented
@zhouyiqing0304 done？

2024-07-22 05:20 UTC, PythonSmall-Q commented
@zhouyiqing0304 好了吗？

2024-07-25 01:05 UTC, PythonSmall-Q commented
@zhouyiqing0304 好了吗喵

2024-07-31 23:56 UTC, closed without merging