深色模式调整题目图片颜色
XMOJ-Script-dev/XMOJ-Script pull request #619
Opened 2024-08-04 06:29 UTC by zhouyiqing0304

## Thank you for your contribution to the XMOJ-Script Community!

Please read the comments below to help us consider your Pull Request.

We are all volunteers and completing the process outlined will help us review your commits quicker.

Please use this pull request template, or your pull request will be closed.

**Please make sure you**

1. Base your code and PRs against the repositories developmental branch.

### When you open a pull request, please delete the text above.
---

**What does this PR aim to accomplish?:**

**How does this PR accomplish the above?:**

---
**By submitting this pull request, I confirm the following:**

1. I have read and understood the [contributors guide](https://github.com/XMOJ-Script-dev/XMOJ-Script/blob/dev/CONTRIBUTING.md), as well as this entire template. I understand which branch to base my commits and Pull Requests against.
2. I have commented my proposed changes within the code and I have tested my changes.
3. I am willing to help maintain this change if there are issues with it later.
4. It is compatible with the [GNU General Public License v3.0](https://github.com/XMOJ-Script-dev/XMOJ-Script/blob/dev/LICENSE)
5. I have squashed any insignificant commits. ([`git rebase`](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html))
6. I have checked that another pull request for this purpose does not exist.
7. I have considered, and confirmed that this submission will be valuable to others.
8. I accept that this submission may not be used, and the pull request closed at the will of the maintainer.
9. I give this submission freely, and claim no ownership to its content.

---
- [ ] I have read the above and my PR is ready for review. *Check this box to confirm*
- [ ] 我承认这个功能很抽象

2024-08-04 06:29 UTC, zhouyiqing0304 commented
@boomzero @PythonSmall-Q 
你们看看，不喜勿喷

2024-08-04 06:30 UTC, zhouyiqing0304 commented
![image](https://github.com/user-attachments/assets/fbb169fa-4c07-4282-b2a4-f2521194ddb4)

2024-08-04 06:32 UTC, zhouyiqing0304 commented
![image](https://github.com/user-attachments/assets/16faadf4-ef75-4d88-9780-865b31a93e92)
Edge浏览器有这个功能

2024-08-04 06:34 UTC, PythonSmall-Q commented
@boomzero 你评判吧，我不用深色模式的

2024-08-04 06:34 UTC, zhouyiqing0304 commented
@PythonSmall-Q 你都不觉得这个功能抽象吗

2024-08-04 06:37 UTC, PythonSmall-Q commented
没仔细看，也不想仔细看。看着有点无语

Message ID: ***@***.***>

2024-08-04 06:38 UTC, zhouyiqing0304 commented
我自己都无语

2024-08-04 06:39 UTC, zhouyiqing0304 commented
微软抽象，我脑子也指定有问题

2024-08-04 09:16 UTC, boomzero commented
> ### When you open a pull request, please delete the text above.
...

2024-08-04 09:26 UTC, boomzero requested changes

2024-08-04 09:26 UTC, boomzero commented on XMOJ.user.js
> +                            "ID": "DarkPicture", "Type": "A", "Name": "使用反色的题目图片（开发中，可能不稳定；需要启用暗色模式）"
remove `开发中，可能不稳定`
If it is unstable, disable it by default

2024-08-04 10:08 UTC, boomzero commented on XMOJ.user.js
> +                            "ID": "DarkPicture", "Type": "A", "Name": "使用反色的题目图片（开发中，可能不稳定；需要启用暗色模式）"
But otherwise okay

2024-08-04 13:19 UTC, PythonSmall-Q commented on XMOJ.user.js
> +                            "ID": "DarkPicture", "Type": "A", "Name": "使用反色的题目图片（开发中，可能不稳定；需要启用暗色模式）"
done，他一直不在线

2024-08-04 13:19 UTC, PythonSmall-Q approved these changes

2024-08-04 13:33 UTC, boomzero approved these changes

2024-08-04 13:33 UTC, boomzero commented
Okay

2024-08-04 13:33 UTC, boomzero commented
lgtm

2024-08-04 13:33 UTC, merged

2024-08-04 13:34 UTC, boomzero commented
@PythonSmall-Q sync to dev

2024-08-04 13:49 UTC, boomzero commented
> @PythonSmall-Q sync to dev

先不要merge进去， 我要改一个东西

2024-08-05 01:05 UTC, PythonSmall-Q commented
改好了吗

2024-08-06 05:52 UTC, boomzero commented
Reverted due to #627